### PR TITLE
Removed dist from repo

### PR DESCRIPTION
**Pull request by JPeer264**
Actually the directory `dist` is not necessary in the repo. Those files gets generated anyway locally. 

Or was this in purpose, so that other people can see what will be generated?!

### CODE REVIEW

**Comment by chrisdemars** [comment]
@JPeer264 The `dist` folder is on purpose so that whoever uses this already has there production ready folder setup.

**Comment by JPeer264** [comment]
Ok perfect, I wasn't sure on that.

I still suggest to put `dist` in `.gitignore` so nobody will accidentally push the production ready code. How you think about it?

**Comment by chrisdemars** [comment]
@JPeer264 that is a good question lol. How about adding a note in the README to not push prod ready code to GitHub?

**Comment by JPeer264** [comment]
@chrisdemars the question is if all people really follow the README.

**Pull request closed without merging**
